name: Android build

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Android build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3.4.1
        with:
          java-version: 11
          distribution: "zulu"

      - name: Setup Node.js
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 16
          cache: "npm"

      - name: Cache Gradle Wrapper
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - name: Cache Gradle Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-caches-

      - name: Install depedencies
        run: npm ci

      - name: Generate release apk
        run: cd android && ./gradlew assembleRelease --no-daemon

      - name: Sign release apk
        uses: ilharp/sign-android-release@v1
        id: sign_app
        with:
          releaseDir: android/app/build/outputs/apk/release
          signingKey: ${{ secrets.ANDROID_SIGNING_KEY }}
          keyAlias: ${{ secrets.ANDROID_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
          buildToolsVersion: 30.0.2

      - name: Upload files to current github release
        uses: svenstaro/upload-release-action@2.3.0
      - name: Upload release apk
        uses: actions/upload-artifact@v3
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{steps.sign_app.outputs.signedFile}}
          tag: ${{ github.ref }}
          overwrite: true
